### PR TITLE
Refactor vehicle schema

### LINKED ISSUE #1: Define message format for vehicle ID
We need to define a interoperable message format for vehicle IDs (like XID)

### PR DESCRIPTION
**Pull request by jschlyter**
closes #1

### CODE REVIEW

**Comment by jschlyter** [comment]
Can we decide that all hex representation is in uppercase?

**Comment by Fromell** [comment]
Nope, since both are used in existing implementations..

Den mån 1 okt. 2018 kl 14:39 skrev Jakob Schlyter <notifications@github.com

**Comment by jschlyter** [comment]
The implementer will uppercase before transmission, or we have to define equality. Agreeing on uppercase only is easier.

**Comment by Fromell** [comment]
From a Hex point of view 9F is the same as 9f
Eg. a conversion to hex will give the same result.

What we can not expect is that other company will change their existing
implementations of their
use of TransitCloud ID (deviceID)..

Therefore upper/lower-case needs to be equalized

/A

Den mån 1 okt. 2018 kl 14:42 skrev Jakob Schlyter <notifications@github.com

**Comment by jschlyter** [comment]
No need to change implementations, we just ask them to uppercase when constructing the telegram.

**Pull request merged**
